
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:


development:
  <<: *default
  database: vetkatia
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  database: vetkatia

production:
  <<: *default
  adapter: postgresql
  database: DATABASE_URL
  username: USERNAME
  password:  PASSWORD
